apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

commonLabels:
  env: stage 

namePrefix: stage-

replicas:
- name: dov-bear-deploy
  count: 1

images:
- name: chukmunnlee/dov-bear
  newTag: v2