---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggappv1-deploy
  labels:
    name: bggappv1-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      name: bggappv1-po
      version: v1
  template:
    metadata:
      labels:
        name: bggappv1-po
        version: v1
    spec:
      containers:
      - name: bggappv1-container
        image: stackupiss/bgg-backend:v1
        imagePullPolicy: IfNotPresent
        args:
        - --prefix
        - /v1
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: bggapp-cm
        - secretRef:
            name: bggapp-secret
---
apiVersion: v1
kind: Service
metadata:
  name: bggappv1-svc
  labels:
    name: bggappv1-svc
spec:
  type: ClusterIP
  selector:
    name: bggappv1-po
    version: v1
  ports:
  - port: 3000
    targetPort: 3000

