---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dov-bear-cm
  labels:
    name: dov-bear-cm
    dept: eng
data:
  INSTANCE_NAME: k8s dov-bear configmap

---
apiVersion: v1
kind: Secret
metadata:
  name: dov-bear-secret
  labels:
    name: dov-bear-secret
type: Opaque
data:
  INSTANCE_NAME: azhzIGRvdi1iZWFyIHNlY3JldA==

---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: dov-bear-deploy
  labels:
    name: dov-bear-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      name: dov-bear-po
  template:
    metadata:
      name: dov-bear-po
      labels:
        name: dov-bear-po
        dept: eng
    spec:
      containers:
      - name: dov-bear-container  
        image: ghcr.io/chukmunnlee/dov-bear@sha256:ebb8275212b73275012e5b2cce5ce7913ce33928b56bdb2ccd37616e7867cba2
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: dov-bear-secret
        ports:
        - name: dov-port 
          containerPort: 3000
        livenessProbe:
          httpGet: 
            path: /healthz
            port: 3000
            scheme: HTTP

---
apiVersion: v1 
kind: Service 
metadata:
  name: dov-bear-svc
  labels:
    name: dov-bear-svc
spec:
  type: ClusterIP
  selector:
    name: dov-bear-po
  ports:
  - port: 8080
    targetPort: dov-port
