---
apiVersion: v1
kind: Secret 
metadata: 
  name: mycluster-secret
type: Opaque
data:
  ROOT_PASSWORD: Y2hhbmdlaXQ=
---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster 
metadata:
  name: mycluster-mysql
  labels:
    name: mycluster-mysql
spec:
  replicas: 2
  secretName: mycluster-secret
  volumeSpec:
    persistentVolumeClaim: 
      accessModes:
      - ReadWriteOnce
      storageClassName: do-block-storage
      resources:
        requests:
          storage: 1Gi

---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlDatabase
metadata:
  name: mydb 
spec: 
  database: mydb 
  clusterRef:
    name: mycluster-mysql 
    namespace: myns